stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/cpu_usage.csv
    - src/preprocess.py
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    - src/train.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed
    - models/model.pkl
    - src/evaluate.py
    outs:
    - plots:
        cache: false
    metrics:
    - evaluation.json:
        cache: false
